import('./api-module.js').then(async api=>{
  const session=await api.getSession();if(!session){location.replace('naya-login-b7k4m9q2.html');return}try{if(!await api.isAdmin(session)){api.signOut();location.replace('naya-login-b7k4m9q2.html');return}}catch{location.replace('naya-login-b7k4m9q2.html');return}
  let products=await api.getProducts(session),primaryImage='',additionalImages=[],productVideos=[];const list=document.querySelector('#list'),modal=document.querySelector('#modal'),form=document.querySelector('#form'),statusEl=document.querySelector('#status'),primaryPreview=document.querySelector('#primaryImagePreview'),additionalPreview=document.querySelector('#additionalImagesPreview');
  const videoField=document.createElement('label');videoField.className='field full upload-field';videoField.innerHTML='<span>סרטון מוצר</span><input id="productVideoFiles" type="file" accept="video/mp4,video/webm,video/quicktime"><small>אפשר להעלות MP4, WebM או MOV. מומלץ סרטון קצר ודחוס.</small>';const videoPreview=document.createElement('div');videoPreview.id='productVideosPreview';videoPreview.className='video-preview field full';additionalPreview.after(videoField,videoPreview);
  const logout=document.createElement('button');logout.className='button danger';logout.textContent='יציאה';logout.onclick=()=>{api.signOut();location.replace('naya-login-b7k4m9q2.html')};document.querySelector('.head-actions').append(logout);
  const ordersLink=document.createElement('a');ordersLink.className='button secondary';ordersLink.href='naya-orders-p5t9w2z7.html';ordersLink.textContent='ניהול הזמנות';document.querySelector('.head-actions').prepend(ordersLink);
  const importDescriptions=document.createElement('button');importDescriptions.type='button';
  const usdField=document.createElement('label');usdField.className='field';usdField.innerHTML='<span>מחיר בדולרים - אופציונלי</span><input name="priceUsd" type="number" min="0" step="0.01" placeholder="יחושב אוטומטית אם יישאר ריק"><small>ניתן לקבוע מחיר ידני או להשאיר ריק להמרה אוטומטית</small>';form.elements.price.closest('label').after(usdField);
  function status(message,type='ok'){statusEl.textContent=message;statusEl.className=`status show ${type}`;setTimeout(()=>statusEl.className='status',2500)}
  import('./gallery-admin.js?v=3').then(module=>module.initGalleryAdmin({api,session,products,status}));
  function render(){list.innerHTML=products.map(p=>`<div class="admin-row"><img src="${p.images[0]||''}" alt=""><div><strong>${p.nameHe}</strong><br><small>${p.sku}</small></div><div>${p.price} ש״ח</div><div>${[...(p.colors||[]),...(p.sizes||[]),...(p.styles||[])].join(', ')||'ללא בחירה'}</div><div>${p.active?'מוצג':'מוסתר'}</div><div class="actions"><button class="button secondary move-product" data-up="${p.id}" aria-label="הזזה למעלה">↑</button><button class="button secondary move-product" data-down="${p.id}" aria-label="הזזה למטה">↓</button><button class="button secondary" data-edit="${p.id}">עריכה</button><button class="button danger" data-delete="${p.id}">מחיקה</button></div></div>`).join('')}
  function renderImages(){primaryPreview.innerHTML=primaryImage?`<div class="preview-image primary"><img src="${primaryImage}" alt="תמונה ראשית"><button type="button" data-remove-primary aria-label="הסרת תמונה">×</button><strong>ראשית</strong></div>`:'';additionalPreview.innerHTML=additionalImages.map((src,i)=>`<div class="preview-image"><img src="${src}" alt="תמונה נוספת ${i+1}"><button type="button" data-remove-additional="${i}" aria-label="הסרת תמונה">×</button></div>`).join('');videoPreview.innerHTML=productVideos.map((src,i)=>`<div class="preview-video"><video src="${src}" controls preload="metadata"></video><button type="button" data-remove-video="${i}" aria-label="הסרת סרטון">×</button><strong>סרטון ${i+1}</strong></div>`).join('')}
  function openForm(product){form.reset();primaryImage=product?.images?.[0]||'';additionalImages=product?.images?.slice(1)||[];productVideos=product?.videos?.slice()||[];document.querySelector('#modalTitle').textContent=product?'עריכת מוצר':'הוספת מוצר';if(product){for(const [key,value] of Object.entries(product)){const field=form.elements[key];if(!field||key==='images'||key==='videos')continue;if(field.type==='checkbox')field.checked=!!value;else field.value=Array.isArray(value)?value.join('\n'):value}if(product.regularPrice<=product.price)form.elements.price.value=''}else{form.elements.id.value='';form.elements.sku.value=`NAYA-${String(products.length+1).padStart(3,'0')}`;form.elements.active.checked=true}renderImages();modal.classList.add('open')}
  const readFile=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});
  document.querySelector('#primaryImageFile').addEventListener('change',async e=>{const [file]=e.target.files;if(file)primaryImage=await readFile(file);renderImages();e.target.value=''});document.querySelector('#additionalImageFiles').addEventListener('change',async e=>{const files=[...e.target.files];if(files.length)additionalImages.push(...await Promise.all(files.map(readFile)));renderImages();e.target.value=''});document.querySelector('#productVideoFiles').addEventListener('change',async e=>{const [file]=e.target.files;if(file?.size>50*1024*1024){status('הסרטון חייב להיות קטן מ-50MB','error');e.target.value='';return}if(file)productVideos=[await readFile(file)];renderImages();e.target.value=''});primaryPreview.addEventListener('click',e=>{if(e.target.closest('[data-remove-primary]')){primaryImage='';renderImages()}});additionalPreview.addEventListener('click',e=>{const b=e.target.closest('[data-remove-additional]');if(!b)return;additionalImages.splice(Number(b.dataset.removeAdditional),1);renderImages()});videoPreview.addEventListener('click',e=>{const b=e.target.closest('[data-remove-video]');if(!b)return;productVideos.splice(Number(b.dataset.removeVideo),1);renderImages()});
  document.querySelector('#add').onclick=()=>openForm();document.querySelector('#cancel').onclick=()=>modal.classList.remove('open');list.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]'),up=e.target.closest('[data-up]'),down=e.target.closest('[data-down]');if(up||down){const id=(up||down).dataset[up?'up':'down'],from=products.findIndex(p=>p.id===id),to=from+(up?-1:1);if(to>=0&&to<products.length){[products[from],products[to]]=[products[to],products[from]];render();try{await api.setProductOrder(session,products.map(p=>p.id));status('סדר המוצרים נשמר')}catch(error){products=await api.getProducts(session);render();status(error.message,'error')}}return}if(edit)openForm(products.find(p=>p.id===edit.dataset.edit));if(del&&confirm('למחוק את המוצר?')){try{await api.deleteProductRemote(session,del.dataset.delete);products=await api.getProducts(session);render();status('המוצר נמחק')}catch(error){status(error.message,'error')}}});const values=value=>value.split(/[,\n]/).map(x=>x.trim()).filter(Boolean);
  importDescriptions.onclick=async()=>{importDescriptions.disabled=true;status('מייבא את תיאורי המוצרים...');try{const source=await fetch('_mehadrin-reference.html').then(response=>response.text()),descriptions=new Map();for(const match of source.matchAll(/product(\d+):\s*\{[\s\S]*?desc:\s*`([\s\S]*?)`\s*\}/g)){const sku=`NAYA-${match[1].padStart(3,'0')}`,description=match[2].replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,'').replace(/\n{3,}/g,'\n\n').trim();descriptions.set(sku,description)}let updated=0;for(const product of products){const description=descriptions.get(product.sku);if(description){await api.updateProductDescription(session,product.id,description);updated++}}products=await api.getProducts(session);render();status(`${updated} תיאורים נשמרו ב-Supabase`)}catch(error){status(error.message,'error')}finally{importDescriptions.disabled=false}};
  form.addEventListener('submit',async e=>{e.preventDefault();const saveButton=form.querySelector('button:not([type="button"])'),d=new FormData(form),id=d.get('id')||`product-${crypto.randomUUID()}`;if(!primaryImage){status('יש לבחור תמונה ראשית','error');return}const regularPrice=Number(d.get('regularPrice')),salePrice=d.get('price')?Number(d.get('price')):null;const product={id,sku:d.get('sku').trim(),nameHe:d.get('nameHe').trim(),nameEn:d.get('nameEn').trim(),descriptionHe:d.get('descriptionHe').trim(),descriptionEn:d.get('descriptionEn').trim(),category:d.get('category'),regularPrice,price:salePrice??regularPrice,priceUsd:d.get('priceUsd')?Number(d.get('priceUsd')):null,active:d.get('active')==='on',colors:values(d.get('colors')),sizes:values(d.get('sizes')),styles:values(d.get('styles')),images:[primaryImage,...additionalImages],videos:productVideos};saveButton.disabled=true;saveButton.textContent='שומר...';try{status('שומר את המוצר...');await api.saveProductRemote(session,product);modal.classList.remove('open');form.reset();status('המוצר נשמר ב-Supabase');products=await api.getProducts(session);render()}catch(error){status(error.message,'error')}finally{saveButton.disabled=false;saveButton.textContent='שמירה'}});render();
});
