import('./api-module.js?v=6').then(async api=>{
  const session=await api.getSession();if(!session){location.replace('naya-login-b7k4m9q2.html');return}try{if(!await api.isAdmin(session)){api.signOut();location.replace('naya-login-b7k4m9q2.html');return}}catch{location.replace('naya-login-b7k4m9q2.html');return}
  let products=await api.getProducts(session),primaryImage='',additionalImages=[],imageColors=[],productVideos=[],currentVariants=[];const list=document.querySelector('#list'),modal=document.querySelector('#modal'),form=document.querySelector('#form'),statusEl=document.querySelector('#status'),primaryPreview=document.querySelector('#primaryImagePreview'),additionalPreview=document.querySelector('#additionalImagesPreview'),variantsList=document.querySelector('#variantsList');
  const pageParams=new URLSearchParams(location.search),editorId=pageParams.get('edit'),editorMode=pageParams.has('new')||!!editorId;const editorUrl=id=>`${location.pathname}?${id?`edit=${encodeURIComponent(id)}`:'new=1'}`;if(editorMode)document.body.classList.add('product-editor-page');
  const videoField=document.createElement('label');videoField.className='field full upload-field';videoField.innerHTML='<span>סרטון מוצר</span><input id="productVideoFiles" type="file" accept="video/mp4,video/webm,video/quicktime"><small>אפשר להעלות MP4, WebM או MOV. מומלץ סרטון קצר ודחוס.</small>';const videoPreview=document.createElement('div');videoPreview.id='productVideosPreview';videoPreview.className='video-preview field full';additionalPreview.after(videoField,videoPreview);
  const logout=document.createElement('button');logout.className='button danger';logout.textContent='יציאה';logout.onclick=()=>{api.signOut();location.replace('naya-login-b7k4m9q2.html')};document.querySelector('.head-actions').append(logout);
  const ordersLink=document.createElement('a');ordersLink.className='button secondary';ordersLink.href='naya-orders-p5t9w2z7.html';ordersLink.textContent='ניהול הזמנות';document.querySelector('.head-actions').prepend(ordersLink);
  const importDescriptions=document.createElement('button');importDescriptions.type='button';
  const usdField=document.createElement('label');usdField.className='field';usdField.innerHTML='<span>מחיר בדולרים - אופציונלי</span><input name="priceUsd" type="number" min="0" step="0.01" placeholder="יחושב אוטומטית אם יישאר ריק"><small>ניתן לקבוע מחיר ידני או להשאיר ריק להמרה אוטומטית</small>';form.elements.price.closest('label').after(usdField);
  function status(message,type='ok'){statusEl.textContent=message;statusEl.className=`status show ${type}`;setTimeout(()=>statusEl.className='status',2500)}
  import('./gallery-admin.js?v=3').then(module=>module.initGalleryAdmin({api,session,products,status}));
  function render(){list.innerHTML=products.map(p=>`<div class="admin-row"><img src="${p.images[0]||''}" alt=""><div><strong>${p.nameHe}</strong><br><small>${p.sku}</small></div><div>${p.price} ש״ח</div><div>${[...(p.colors||[]),...(p.sizes||[]),...(p.styles||[])].join(', ')||'ללא בחירה'}</div><div>${p.active?'מוצג':'מוסתר'}</div><div class="actions"><button class="button secondary move-product" data-up="${p.id}" aria-label="הזזה למעלה">↑</button><button class="button secondary move-product" data-down="${p.id}" aria-label="הזזה למטה">↓</button><button class="button secondary" data-edit="${p.id}">עריכה</button><button class="button danger" data-delete="${p.id}">מחיקה</button></div></div>`).join('')}
  const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const imageColorSelect=index=>`<select data-image-color="${index}" aria-label="צבע לתמונה"><option value="">ללא שיוך לצבע</option>${values(form.elements.colors.value).map(color=>`<option value="${escapeHtml(color)}" ${imageColors[index]===color?'selected':''}>${escapeHtml(color)}</option>`).join('')}</select>`;
  function renderImages(){primaryPreview.innerHTML=primaryImage?`<div class="preview-image primary"><img src="${primaryImage}" alt="תמונה ראשית"><button type="button" data-remove-primary aria-label="הסרת תמונה">×</button><strong>ראשית</strong>${imageColorSelect(0)}</div>`:'';additionalPreview.innerHTML=additionalImages.map((src,i)=>`<div class="preview-image"><img src="${src}" alt="תמונה נוספת ${i+1}"><button type="button" data-remove-additional="${i}" aria-label="הסרת תמונה">×</button>${imageColorSelect(i+1)}</div>`).join('');videoPreview.innerHTML=productVideos.map((src,i)=>`<div class="preview-video"><video src="${src}" controls preload="metadata"></video><button type="button" data-remove-video="${i}" aria-label="הסרת סרטון">×</button><strong>סרטון ${i+1}</strong></div>`).join('')}
  const variantKey=variant=>[variant.color||'',variant.size||'',variant.style||''].join('|');
  function createVariantCombinations(){const colors=values(form.elements.colors.value),sizes=values(form.elements.sizes.value),styles=values(form.elements.styles.value),axes=[colors.length?colors:[''],sizes.length?sizes:[''],styles.length?styles:['']],old=new Map(currentVariants.map(item=>[variantKey(item),item]));currentVariants=[];for(const color of axes[0])for(const size of axes[1])for(const style of axes[2]){if(!color&&!size&&!style)continue;const base={color,size,style},saved=old.get(variantKey(base));currentVariants.push({...base,price:saved?.price??''})}renderVariants()}
  function renderVariants(){variantsList.innerHTML=currentVariants.length?`<p class="variants-count">נוצרו ${currentVariants.length} שילובים</p>`+currentVariants.map((variant,index)=>`<div class="variant-row"><div class="variant-values">${variant.color?`<span><b>צבע:</b> ${escapeHtml(variant.color)}</span>`:''}${variant.size?`<span><b>מידה:</b> ${escapeHtml(variant.size)}</span>`:''}${variant.style?`<span><b>אפשרות:</b> ${escapeHtml(variant.style)}</span>`:''}</div><label>מחיר ש״ח<input type="number" min="0" step="0.01" data-variant-price="${index}" value="${escapeHtml(variant.price??'')}" placeholder="מחיר רגיל"></label></div>`).join(''):'<p class="variants-empty">הוסף צבעים, מידות או אפשרויות ולחץ „יצירת כל השילובים”.</p>'}
  function setRichValue(name,value=''){const wrapper=document.querySelector(`[data-rich-field="${name}"]`),editor=wrapper.querySelector('.rich-editor'),field=form.elements[name];const looksHtml=/<\/?[a-z][\s\S]*>/i.test(value);editor.innerHTML=looksHtml?value:escapeHtml(value).replace(/\n/g,'<br>');field.value=editor.innerHTML}
  function syncRichEditors(){document.querySelectorAll('[data-rich-field]').forEach(wrapper=>{form.elements[wrapper.dataset.richField].value=wrapper.querySelector('.rich-editor').innerHTML.trim()})}
  function openForm(product){form.reset();primaryImage=product?.images?.[0]||'';additionalImages=product?.images?.slice(1)||[];imageColors=product?.imageColors?.slice()||Array(product?.images?.length||0).fill('');productVideos=product?.videos?.slice()||[];currentVariants=product?.variants?.map(item=>({...item}))||[];document.querySelector('#modalTitle').textContent=product?'עריכת מוצר':'הוספת מוצר';if(product){for(const [key,value] of Object.entries(product)){const field=form.elements[key];if(!field||['images','imageColors','videos','variants','descriptionHe','descriptionEn'].includes(key))continue;if(field.type==='checkbox')field.checked=!!value;else field.value=Array.isArray(value)?value.join('\n'):value}if(product.regularPrice<=product.price)form.elements.price.value=''}else{form.elements.id.value='';form.elements.sku.value=`NAYA-${String(products.length+1).padStart(3,'0')}`;form.elements.active.checked=true}setRichValue('descriptionHe',product?.descriptionHe||'');setRichValue('descriptionEn',product?.descriptionEn||'');renderImages();renderVariants();modal.classList.add('open')}
  const readFile=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});
  document.querySelector('#primaryImageFile').addEventListener('change',async e=>{const [file]=e.target.files;if(file){primaryImage=await readFile(file);imageColors[0]=''}renderImages();e.target.value=''});document.querySelector('#additionalImageFiles').addEventListener('change',async e=>{const files=[...e.target.files];if(files.length){additionalImages.push(...await Promise.all(files.map(readFile)));imageColors.push(...files.map(()=>''))}renderImages();e.target.value=''});document.querySelector('#productVideoFiles').addEventListener('change',async e=>{const [file]=e.target.files;if(file?.size>50*1024*1024){status('הסרטון חייב להיות קטן מ-50MB','error');e.target.value='';return}if(file)productVideos=[await readFile(file)];renderImages();e.target.value=''});const setImageColor=e=>{const select=e.target.closest('[data-image-color]');if(select)imageColors[Number(select.dataset.imageColor)]=select.value};primaryPreview.addEventListener('change',setImageColor);additionalPreview.addEventListener('change',setImageColor);form.elements.colors.addEventListener('change',renderImages);primaryPreview.addEventListener('click',e=>{if(e.target.closest('[data-remove-primary]')){primaryImage='';imageColors[0]='';renderImages()}});additionalPreview.addEventListener('click',e=>{const b=e.target.closest('[data-remove-additional]');if(!b)return;const index=Number(b.dataset.removeAdditional);additionalImages.splice(index,1);imageColors.splice(index+1,1);renderImages()});videoPreview.addEventListener('click',e=>{const b=e.target.closest('[data-remove-video]');if(!b)return;productVideos.splice(Number(b.dataset.removeVideo),1);renderImages()});
  document.querySelector('#generateVariants').onclick=createVariantCombinations;variantsList.addEventListener('input',e=>{const input=e.target.closest('[data-variant-price]');if(input)currentVariants[Number(input.dataset.variantPrice)].price=input.value});
  document.querySelectorAll('.rich-toolbar').forEach(toolbar=>toolbar.addEventListener('click',e=>{const button=e.target.closest('[data-command]');if(!button)return;const editor=toolbar.parentElement.querySelector('.rich-editor'),command=button.dataset.command;editor.focus();if(command==='createLink'){const url=prompt('כתובת הקישור');if(url)document.execCommand(command,false,url)}else document.execCommand(command,false,null)}));
  document.querySelector('#add').onclick=()=>window.open(editorUrl(),'_blank');document.querySelector('#cancel').onclick=()=>{if(editorMode){window.close();if(!window.closed)location.href=location.pathname}else modal.classList.remove('open')};list.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]'),up=e.target.closest('[data-up]'),down=e.target.closest('[data-down]');if(up||down){const id=(up||down).dataset[up?'up':'down'],from=products.findIndex(p=>p.id===id),to=from+(up?-1:1);if(to>=0&&to<products.length){[products[from],products[to]]=[products[to],products[from]];render();try{await api.setProductOrder(session,products.map(p=>p.id));status('סדר המוצרים נשמר')}catch(error){products=await api.getProducts(session);render();status(error.message,'error')}}return}if(edit)window.open(editorUrl(edit.dataset.edit),'_blank');if(del&&confirm('למחוק את המוצר?')){try{await api.deleteProductRemote(session,del.dataset.delete);products=await api.getProducts(session);render();status('המוצר נמחק')}catch(error){status(error.message,'error')}}});const values=value=>String(value||'').split(/[,\n]/).map(x=>x.trim()).filter(Boolean);
  ['colors','sizes','styles'].forEach(name=>form.elements[name].addEventListener('change',()=>{createVariantCombinations();if(name==='colors')renderImages()}));
  importDescriptions.onclick=async()=>{importDescriptions.disabled=true;status('מייבא את תיאורי המוצרים...');try{const source=await fetch('_mehadrin-reference.html').then(response=>response.text()),descriptions=new Map();for(const match of source.matchAll(/product(\d+):\s*\{[\s\S]*?desc:\s*`([\s\S]*?)`\s*\}/g)){const sku=`NAYA-${match[1].padStart(3,'0')}`,description=match[2].replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,'').replace(/\n{3,}/g,'\n\n').trim();descriptions.set(sku,description)}let updated=0;for(const product of products){const description=descriptions.get(product.sku);if(description){await api.updateProductDescription(session,product.id,description);updated++}}products=await api.getProducts(session);render();status(`${updated} תיאורים נשמרו ב-Supabase`)}catch(error){status(error.message,'error')}finally{importDescriptions.disabled=false}};
  form.addEventListener('submit',async event=>{
    event.preventDefault();
    syncRichEditors();
    const saveButton=form.querySelector('button:not([type="button"])');
    const data=new FormData(form);
    const id=data.get('id')||`product-${crypto.randomUUID()}`;
    if(!primaryImage){status('יש לבחור תמונה ראשית','error');return}
    const regularPrice=Number(data.get('regularPrice'));
    const salePrice=data.get('price')?Number(data.get('price')):null;
    const product={
      id,sku:data.get('sku').trim(),nameHe:data.get('nameHe').trim(),nameEn:data.get('nameEn').trim(),
      descriptionHe:data.get('descriptionHe').trim(),descriptionEn:data.get('descriptionEn').trim(),
      category:data.get('category'),regularPrice,price:salePrice??regularPrice,
      priceUsd:data.get('priceUsd')?Number(data.get('priceUsd')):null,active:data.get('active')==='on',
      colors:values(data.get('colors')),sizes:values(data.get('sizes')),styles:values(data.get('styles')),
      variants:currentVariants.map(item=>({...item,price:item.price===''?null:Number(item.price)})),
      images:[primaryImage,...additionalImages],imageColors:[...imageColors],videos:productVideos
    };
    saveButton.disabled=true;saveButton.textContent='שומר...';
    try{status('שומר את המוצר...');await api.saveProductRemote(session,product);form.reset();status('המוצר נשמר ב-Supabase');if(editorMode){window.opener?.postMessage({type:'naya-product-saved'},location.origin);setTimeout(()=>{window.close();if(!window.closed)location.href=location.pathname},650)}else{modal.classList.remove('open');products=await api.getProducts(session);render()}}
    catch(error){status(error.message,'error')}
    finally{saveButton.disabled=false;saveButton.textContent='שמירה'}
  });
  window.addEventListener('message',async event=>{if(event.origin!==location.origin||event.data?.type!=='naya-product-saved')return;products=await api.getProducts(session);render();status('רשימת המוצרים עודכנה')});
  render();if(editorMode){document.querySelector('.product-admin-header .head-actions').hidden=true;form.prepend(statusEl);document.querySelector('.admin-shell').hidden=true;const product=editorId?products.find(item=>item.id===editorId):null;if(editorId&&!product){status('המוצר לא נמצא','error')}else openForm(product)}
});
