const SUPABASE_URL='https://ejzwceuoxzwtpkoovoma.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_Kry0TasR3z09TPvXzeI3dA_xryw8shH';
const SESSION_KEY='naya_admin_session_v1';

async function request(path,{method='GET',body,token,headers={}}={}){
  const response=await fetch(`${SUPABASE_URL}${path}`,{method,headers:{apikey:PUBLISHABLE_KEY,Authorization:`Bearer ${token||PUBLISHABLE_KEY}`,'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});
  const data=await response.json().catch(()=>null);
  if(!response.ok)throw new Error(data?.error||data?.msg||data?.message||data?.error_description||`Request failed (${response.status})`);
  return data;
}

export async function signIn(email,password){const data=await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email,password}});const session={accessToken:data.access_token,refreshToken:data.refresh_token,expiresAt:Date.now()+data.expires_in*1000,user:data.user};localStorage.setItem(SESSION_KEY,JSON.stringify(session));return session}
export function signOut(){localStorage.removeItem(SESSION_KEY)}
export async function getSession(){let session;try{session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}if(!session)return null;if(Date.now()<session.expiresAt-60000)return session;try{const data=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:session.refreshToken}});session={accessToken:data.access_token,refreshToken:data.refresh_token,expiresAt:Date.now()+data.expires_in*1000,user:data.user};localStorage.setItem(SESSION_KEY,JSON.stringify(session));return session}catch{signOut();return null}}
export async function isAdmin(session){return request('/rest/v1/rpc/is_naya_admin',{method:'POST',body:{},token:session.accessToken})}
const publicImageUrl=path=>path.startsWith('http')||path.startsWith('data:')||path.startsWith('../')||/^model\d+\.jpg$/i.test(path)?path:path.startsWith('products-images/')?`../${path}`:`${SUPABASE_URL}/storage/v1/object/public/naya-product-images/${path}`;
const isVideoPath=path=>/\.(mp4|webm|mov|m4v)(?:$|\?)/i.test(path)||String(path).startsWith('data:video/');
const mapProduct=row=>{const media=(row.product_images||[]).sort((a,b)=>Number(b.is_primary)-Number(a.is_primary)||a.sort_order-b.sort_order),imageRows=media.filter(item=>!isVideoPath(item.storage_path)),videoRows=media.filter(item=>isVideoPath(item.storage_path)),ilsPrice=Number(row.price_ils),roundedUsd=Math.max(1,Math.round(ilsPrice/3.7));return {id:row.id,sortOrder:Number(row.sort_order)||0,sku:row.sku,nameHe:row.name_he,nameEn:row.name_en,descriptionHe:row.description_he,descriptionEn:row.description_en,category:row.category,regularPrice:Number(row.regular_price_ils),price:ilsPrice,priceUsd:row.price_usd===null?roundedUsd:Number(row.price_usd),active:row.active,variants:Array.isArray(row.variants)?row.variants:[],images:imageRows.map(item=>publicImageUrl(item.storage_path)),imageColors:imageRows.map(item=>item.color_value||''),videos:videoRows.map(item=>publicImageUrl(item.storage_path)),colors:(row.product_options||[]).filter(o=>o.option_type==='color'&&o.active).sort((a,b)=>a.sort_order-b.sort_order).map(o=>o.value_he),sizes:(row.product_options||[]).filter(o=>o.option_type==='size'&&o.active).sort((a,b)=>a.sort_order-b.sort_order).map(o=>o.value_he),styles:(row.product_options||[]).filter(o=>o.option_type==='style'&&o.active).sort((a,b)=>a.sort_order-b.sort_order).map(o=>o.value_he)}};
export async function getProducts(session){const rows=await request('/rest/v1/products?select=*,product_images(*),product_options(*)&order=sort_order.asc,created_at.asc',{token:session?.accessToken}),products=rows.map(mapProduct),orders=products.map(product=>product.sortOrder),hasDuplicateOrder=new Set(orders).size!==orders.length;if(hasDuplicateOrder)products.sort((a,b)=>{const aNumber=Number(String(a.sku||'').match(/\d+$/)?.[0])||0,bNumber=Number(String(b.sku||'').match(/\d+$/)?.[0])||0;return aNumber-bNumber||String(a.sku||'').localeCompare(String(b.sku||''))});return products}
const storagePathFromUrl=url=>{const marker='/storage/v1/object/public/naya-product-images/';return url.includes(marker)?url.split(marker)[1]:url.replace(/^\.\.\//,'')};
async function uploadDataMedia(session,productId,dataUrl){const blob=await(await fetch(dataUrl)).blob(),rawExt=blob.type.split('/')[1]||'bin',ext=rawExt.replace('jpeg','jpg').replace('quicktime','mov'),path=`${productId}/${crypto.randomUUID()}.${ext}`,response=await fetch(`${SUPABASE_URL}/storage/v1/object/naya-product-images/${path}`,{method:'POST',headers:{apikey:PUBLISHABLE_KEY,Authorization:`Bearer ${session.accessToken}`,'Content-Type':blob.type,'x-upsert':'false'},body:blob});if(!response.ok)throw new Error(blob.type.startsWith('video/')?'העלאת הסרטון נכשלה':'העלאת התמונה נכשלה');return path}
export async function saveProductRemote(session,product){const row={sku:product.sku,name_he:product.nameHe,name_en:product.nameEn,description_he:product.descriptionHe||'',description_en:product.descriptionEn||'',category:product.category,regular_price_ils:product.regularPrice,price_ils:product.price,price_usd:product.priceUsd,active:product.active,variants:product.variants||[]};let saved;if(/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(product.id||'')){saved=(await request(`/rest/v1/products?id=eq.${product.id}`,{method:'PATCH',body:row,token:session.accessToken,headers:{Prefer:'return=representation'}}))[0]}else{saved=(await request('/rest/v1/products',{method:'POST',body:row,token:session.accessToken,headers:{Prefer:'return=representation'}}))[0]}await request(`/rest/v1/product_images?product_id=eq.${saved.id}`,{method:'DELETE',token:session.accessToken});await request(`/rest/v1/product_options?product_id=eq.${saved.id}`,{method:'DELETE',token:session.accessToken});const media=[...(product.images||[]).map((item,index)=>({item,colorValue:product.imageColors?.[index]||''})),...(product.videos||[]).map(item=>({item,colorValue:''}))],uploaded=[];for(const entry of media)uploaded.push({storage_path:entry.item.startsWith('data:')?await uploadDataMedia(session,saved.id,entry.item):storagePathFromUrl(entry.item),color_value:entry.colorValue||null});if(uploaded.length)await request('/rest/v1/product_images',{method:'POST',body:uploaded.map((entry,i)=>({product_id:saved.id,storage_path:entry.storage_path,color_value:entry.color_value,is_primary:i===0&&!isVideoPath(entry.storage_path),sort_order:i})),token:session.accessToken});const optionRows=[];for(const [type,values] of Object.entries({color:product.colors||[],size:product.sizes||[],style:product.styles||[]}))values.forEach((value_he,sort_order)=>optionRows.push({product_id:saved.id,option_type:type,value_he,value_en:value_he,sort_order}));if(optionRows.length)await request('/rest/v1/product_options',{method:'POST',body:optionRows,token:session.accessToken});return saved}
export async function updateProductDescription(session,id,descriptionHe){return request(`/rest/v1/products?id=eq.${id}`,{method:'PATCH',body:{description_he:descriptionHe},token:session.accessToken,headers:{Prefer:'return=minimal'}})}
export async function deleteProductRemote(session,id){await request(`/rest/v1/products?id=eq.${id}`,{method:'DELETE',token:session.accessToken})}
export async function createOrder(customer,items){let order=await request('/rest/v1/rpc/create_naya_order',{method:'POST',body:{p_customer:customer,p_items:items}});if(order?.id){sessionStorage.setItem('naya_pending_order_id',order.id);try{order=await request('/rest/v1/rpc/apply_naya_order_promotion',{method:'POST',body:{p_order_id:order.id}})||order}catch{}}return order}
export async function startTranzilaPayment(orderId){return request('/functions/v1/naya-tranzila',{method:'POST',body:{action:'start',order_id:orderId}})}
export async function startPayPalPayment(orderId){return request('/functions/v1/naya-paypal',{method:'POST',body:{action:'start',order_id:orderId}})}
export async function getPayPalConfig(){return request('/functions/v1/naya-paypal?action=config')}
export async function capturePayPalPayment(orderId,paypalOrderId,fundingSource){return request('/functions/v1/naya-paypal',{method:'POST',body:{action:'capture',order_id:orderId,paypal_order_id:paypalOrderId,funding_source:fundingSource}})}
export async function sendOrderEmails(orderId){return request('/functions/v1/naya-order-email',{method:'POST',body:{order_id:orderId}})}
export async function sendShipmentEmail(session,orderId){return request('/functions/v1/naya-order-email',{method:'POST',body:{action:'shipped',order_id:orderId},token:session.accessToken})}
export async function getOrders(session){return request('/rest/v1/orders?select=*,order_items(*)&order=created_at.desc',{token:session.accessToken})}
export async function setProductOrder(session,ids){for(let index=0;index<ids.length;index++)await request(`/rest/v1/products?id=eq.${ids[index]}`,{method:'PATCH',body:{sort_order:index},token:session.accessToken})}
export async function getPromotionSettings(session){const rows=await request('/rest/v1/store_promotions?id=eq.quantity_offer&select=enabled',{token:session?.accessToken});return {enabled:rows[0]?.enabled!==false}}
export async function setPromotionEnabled(session,enabled){return request('/rest/v1/store_promotions?id=eq.quantity_offer',{method:'PATCH',body:{enabled:!!enabled,updated_at:new Date().toISOString()},token:session.accessToken,headers:{Prefer:'return=representation'}})}
export async function updateOrder(session,id,changes){return request(`/rest/v1/orders?id=eq.${id}`,{method:'PATCH',body:changes,token:session.accessToken,headers:{Prefer:'return=representation'}})}
export async function deleteOrder(session,id){return request(`/rest/v1/orders?id=eq.${id}`,{method:'DELETE',token:session.accessToken})}
export async function getModelGallery(session){const rows=await request('/rest/v1/model_gallery?select=*&order=sort_order.asc,created_at.asc',{token:session?.accessToken,headers:{'Cache-Control':'no-cache'}});return rows.map(row=>({id:row.id,image:publicImageUrl(row.image_path),productId:row.product_id,sortOrder:row.sort_order,active:row.active}))}
export async function saveModelGalleryItem(session,item){const imagePath=item.image.startsWith('data:')?await uploadDataMedia(session,'model-gallery',item.image):storagePathFromUrl(item.image),row={image_path:imagePath,product_id:item.productId||null,sort_order:item.sortOrder||0,active:item.active!==false};if(item.id)return request(`/rest/v1/model_gallery?id=eq.${item.id}`,{method:'PATCH',body:row,token:session.accessToken,headers:{Prefer:'return=representation'}});return request('/rest/v1/model_gallery',{method:'POST',body:row,token:session.accessToken,headers:{Prefer:'return=representation'}})}
export async function deleteModelGalleryItem(session,id){return request(`/rest/v1/model_gallery?id=eq.${id}`,{method:'DELETE',token:session.accessToken})}
export async function setModelGalleryOrder(session,ids){for(let index=0;index<ids.length;index++)await request(`/rest/v1/model_gallery?id=eq.${ids[index]}`,{method:'PATCH',body:{sort_order:index},token:session.accessToken})}
export {SUPABASE_URL,PUBLISHABLE_KEY,request};
