export async function initGalleryAdmin({api,session,products,status}){
  const section=document.createElement('section');
  section.className='admin-gallery-manager';
  section.innerHTML='<div class="gallery-admin-head"><div><h2>עריכת גלריית המודלים</h2><p>העלאה או החלפה של תמונה ושיוך אופציונלי למוצר</p></div><button class="button" type="button" id="addGalleryImage">+ תמונת מודל</button></div><div id="galleryAdminNotice" class="gallery-admin-notice"></div><div id="galleryAdminGrid" class="gallery-admin-grid"></div>';
  document.querySelector('.admin-shell').append(section);
  const grid=section.querySelector('#galleryAdminGrid'),notice=section.querySelector('#galleryAdminNotice');
  let items=[];
  try{items=await api.getModelGallery(session)}catch{items=Array.from({length:15},(_,index)=>({id:null,image:`model${index+1}.jpg`,productId:null,sortOrder:index,active:true}));notice.textContent='הגלריה מוצגת במצב התחלתי. יש להפעיל פעם אחת את קובץ הגדרת הגלריה בסופאבייס כדי לשמור שינויים.'}
  const productOptions=selected=>'<option value="">ללא קישור למוצר</option>'+products.map(product=>`<option value="${product.id}" ${product.id===selected?'selected':''}>${product.nameHe} - ${product.sku}</option>`).join('');
  function render(){grid.innerHTML=items.map((item,index)=>`<article class="gallery-admin-card" data-gallery-index="${index}"><img src="${item.image}" alt="תמונת מודל ${index+1}"><label class="gallery-replace">החלפת תמונה<input type="file" accept="image/*" data-gallery-file="${index}"></label><label>קישור למוצר<select data-gallery-product="${index}">${productOptions(item.productId)}</select></label><label class="gallery-active"><input type="checkbox" data-gallery-active="${index}" ${item.active!==false?'checked':''}> מוצגת בגלריה</label><div class="gallery-admin-actions"><button class="button secondary" type="button" data-gallery-up="${index}" ${index===0?'disabled':''}>↑</button><button class="button secondary" type="button" data-gallery-down="${index}" ${index===items.length-1?'disabled':''}>↓</button><button class="button" type="button" data-gallery-save="${index}">שמירה</button><button class="button danger" type="button" data-gallery-delete="${index}">מחיקה</button></div></article>`).join('')}
  const readFile=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});
  async function saveItem(index,message='תמונת הגלריה נשמרה'){const item=items[index];if(!item?.image){status('יש לבחור תמונה','error');return}status('שומר את תמונת הגלריה...');await api.saveModelGalleryItem(session,{...item,sortOrder:index});items=await api.getModelGallery(session);notice.textContent='';render();status(message)}
  const headerAdd=document.querySelector('#addGalleryHeader');
  const addItem=()=>{items.push({id:null,image:'',productId:null,sortOrder:items.length,active:true});render();section.scrollIntoView({behavior:'smooth',block:'start'});requestAnimationFrame(()=>grid.querySelector('[data-gallery-index]:last-child input[type="file"]')?.click())};
  section.querySelector('#addGalleryImage').onclick=addItem;
  if(headerAdd){headerAdd.disabled=false;headerAdd.onclick=addItem}
  grid.addEventListener('change',async event=>{const fileInput=event.target.closest('[data-gallery-file]'),productSelect=event.target.closest('[data-gallery-product]'),activeInput=event.target.closest('[data-gallery-active]');if(fileInput?.files[0]){const index=Number(fileInput.dataset.galleryFile);items[index].image=await readFile(fileInput.files[0]);render();try{await saveItem(index,'התמונה הועלתה ונשמרה אוטומטית')}catch(error){status(error.message,'error')}return}if(productSelect)items[Number(productSelect.dataset.galleryProduct)].productId=productSelect.value||null;if(activeInput)items[Number(activeInput.dataset.galleryActive)].active=activeInput.checked});
  grid.addEventListener('click',async event=>{const up=event.target.closest('[data-gallery-up]'),down=event.target.closest('[data-gallery-down]'),save=event.target.closest('[data-gallery-save]'),del=event.target.closest('[data-gallery-delete]');if(up||down){const from=Number((up||down).dataset[up?'galleryUp':'galleryDown']),to=from+(up?-1:1);[items[from],items[to]]=[items[to],items[from]];render();const ids=items.map(item=>item.id).filter(Boolean);if(ids.length===items.length)try{await api.setModelGalleryOrder(session,ids);status('סדר הגלריה נשמר')}catch(error){status(error.message,'error')}return}if(save){const index=Number(save.dataset.gallerySave);try{await saveItem(index)}catch(error){status(error.message,'error')}return}if(del){const index=Number(del.dataset.galleryDelete),item=items[index];if(!confirm('למחוק את התמונה מהגלריה?'))return;try{if(item.id)await api.deleteModelGalleryItem(session,item.id);items.splice(index,1);render();status('התמונה הוסרה מהגלריה')}catch(error){status(error.message,'error')}}});
  render();
}
