const productsEl=document.querySelector('#products'),searchEl=document.querySelector('#search'),categoryEl=document.querySelector('#category'),drawer=document.querySelector('#cartDrawer');
const CART_KEY='naya_new_store_cart_v2',RATE_KEY='naya_usd_ils_rate';let products=NayaCatalog.get(),cart=JSON.parse(localStorage.getItem(CART_KEY)||'{}'),language=localStorage.getItem('naya_store_language')||'he',usdRate=Number(localStorage.getItem(RATE_KEY))||null;
import('./api-module.js').then(api=>api.getProducts()).then(remote=>{if(remote.length){products=remote.map(mergeProductSizes);renderProducts();renderCart()}}).catch(()=>{});
const languageButton=document.querySelector('#langToggle');
document.querySelector('#checkout').addEventListener('click',e=>{e.stopImmediatePropagation();location.href='checkout.html'},true);
const text={he:{shop:'התכשיט שלך מחכה לך',sub:'החנות החדשה של Naya - סביבת בדיקה פרטית',search:'חיפוש מוצר',all:'כל הקטגוריות',necklaces:'שרשראות',rings:'טבעות',bracelets:'צמידים',color:'צבע',size:'מידה',style:'אפשרות',choose:'נא לבחור',add:'הוספה לעגלה',empty:'לא נמצאו מוצרים',cart:'סל הקניות',remove:'הסרה',total:'סה״כ',emptyCart:'הסל עדיין ריק',checkout:"המשך לצ'ק אאוט",notice:'מצב בדיקה - לא מתבצע חיוב',continueShopping:'חזרה לחנות',lang:'English'},en:{shop:'Find your perfect jewelry',sub:'The new Naya store - private test environment',search:'Search products',all:'All categories',necklaces:'Necklaces',rings:'Rings',bracelets:'Bracelets',color:'Color',size:'Size',style:'Option',choose:'Please choose',add:'Add to cart',empty:'No products found',cart:'Shopping cart',remove:'Remove',total:'Estimated total',emptyCart:'Your cart is empty',checkout:'Continue to checkout',notice:'USD prices are for display. The final charge will be processed in ILS.',continueShopping:'Continue Shopping',lang:'עברית'}};
const t=key=>text[language][key];
const usdAmount=(amount,product)=>{const ils=Number(amount),manual=Number(product?.priceUsd),isSalePrice=Number(product?.price)===ils;if(isSalePrice&&manual>0)return Math.round(manual);if(!Number.isFinite(ils)||ils<=0)return null;return Math.max(1,Math.round(ils/3.7))};
const usdPrice=p=>usdAmount(p.price,p);
const money=(amount,product)=>{if(language==='he')return `${Number(amount).toLocaleString('he-IL')} ש״ח`;const usd=usdAmount(amount,product);return usd!==null?`$${usd.toFixed(2)}`:'$--'};
const optionTranslations={'זהב':'Gold','צבע זהב':'Gold','מוזהב':'Gold','כסף':'Silver','כסוף':'Silver','צבע כסף':'Silver','מוכסף':'Silver','רוז גולד':'Rose Gold','זהב ורוד':'Rose Gold','שחור':'Black','לבן':'White','כחול':'Blue','אדום':'Red','ירוק':'Green','קצר':'Short','קצרה':'Short','ארוך':'Long','ארוכה':'Long','קטן':'Small','קטנה':'Small','בינוני':'Medium','בינונית':'Medium','גדול':'Large','גדולה':'Large','מתכוונן':'Adjustable','מתכווננת':'Adjustable','נשים':'Women','גברים':'Men'};
const optionText=value=>{const raw=String(value).trim();if(language!=='en')return raw;return optionTranslations[raw]||raw.replace(/מילימטרים/g,'millimeters').replace(/מילימטר/g,'millimeter').replace(/ס\s*["״']?\s*מ/g,'cm').replace(/מ\s*["״']?\s*מ/g,'mm').replace(/קצרה|קצר/g,'Short').replace(/ארוכה|ארוך/g,'Long').replace(/קטנה|קטן/g,'Small').replace(/בינונית|בינוני/g,'Medium').replace(/גדולה|גדול/g,'Large').replace(/מתכווננת|מתכוונן/g,'Adjustable')};
const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const variantSelect=(label,name,values)=>values?.length?`<label><select name="${name}" required aria-label="${escapeHtml(label)}"><option value="" selected>${escapeHtml(label)}</option>${values.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(optionText(v))}</option>`).join('')}</select></label>`:'';
const combinedSizeOptions=product=>{const sizes=(product.sizes||[]).filter(Boolean),styles=(product.styles||[]).filter(Boolean);if(!styles.length)return sizes;if(!sizes.length)return styles;if(styles.length===1)return sizes.map(size=>`${size} - ${styles[0]}`);if(styles.length===sizes.length)return sizes.map((size,index)=>`${size} - ${styles[index]}`);return sizes.flatMap(size=>styles.map(style=>`${size} - ${style}`))};
function mergeProductSizes(product){return {...product,sizes:combinedSizeOptions(product),styles:[]}}
products=products.map(mergeProductSizes);
const imageForColor=(product,color)=>{const index=(product.imageColors||[]).findIndex(value=>value===color);return index>=0?product.images[index]:product.images[0]};
const selectedVariant=(product,choice={})=>(product.variants||[]).find(variant=>{const sizeLabel=[variant.size,variant.style].filter(Boolean).join(' - ');return (!variant.color||variant.color===choice.color)&&(!sizeLabel||sizeLabel===choice.size)});
const selectedPrice=(product,choice)=>{const value=selectedVariant(product,choice)?.price;return value!==null&&value!==''&&Number.isFinite(Number(value))?Number(value):product.price};
const cleanDescription=value=>{const template=document.createElement('template');template.innerHTML=String(value||'').replace(/\n/g,'<br>');template.content.querySelectorAll('*').forEach(node=>{if(!['BR','B','STRONG','I','EM','U','UL','OL','LI','A','P','DIV'].includes(node.tagName)){node.replaceWith(...node.childNodes);return}[...node.attributes].forEach(attribute=>{if(!(node.tagName==='A'&&attribute.name==='href'))node.removeAttribute(attribute.name)});if(node.tagName==='A'&&!/^https?:\/\//i.test(node.getAttribute('href')||''))node.removeAttribute('href')});return template.innerHTML};
async function loadRate(){try{const response=await fetch('https://www.boi.org.il/PublicApi/GetExchangeRates?');const data=await response.json(),usd=data.exchangeRates?.find(x=>x.key==='USD')?.currentExchangeRate;if(usd){usdRate=Number(usd);localStorage.setItem(RATE_KEY,String(usdRate));if(language==='en'){renderProducts();renderCart()}}}catch{}}
function applyLanguage(){document.documentElement.lang=language;document.documentElement.dir=language==='he'?'rtl':'ltr';searchEl.placeholder=t('search');categoryEl.options[0].text=t('all');categoryEl.options[1].text=t('necklaces');categoryEl.options[2].text=t('rings');categoryEl.options[3].text=t('bracelets');document.querySelector('.drawer-head h2').textContent=t('cart');document.querySelector('#checkout').textContent=t('checkout');document.querySelector('#continueShopping').textContent=t('continueShopping');document.querySelector('.notice').textContent=t('notice');renderProducts();renderCart()}
function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(cart));renderCart()}
function renderProducts(){const q=searchEl.value.trim().toLowerCase(),cat=categoryEl.value;const list=products.filter(p=>p.active&&(!cat||p.category===cat)&&(!q||p.nameHe.toLowerCase().includes(q)||p.nameEn.toLowerCase().includes(q)||p.sku.toLowerCase().includes(q)));productsEl.innerHTML=list.length?list.map(p=>`<article class="product" data-product="${p.id}"><div class="product-image-wrap"><img src="${p.images[0]}" alt="${language==='he'?p.nameHe:p.nameEn}" loading="lazy"><span class="product-info-badge" aria-hidden="true">i</span></div><div class="product-body"><h2>${language==='he'?p.nameHe:p.nameEn}</h2><div class="variant-fields">${variantSelect(t('color'),'color',p.colors)}${variantSelect(t('size'),'size',p.sizes)}</div><div class="price-row">${p.regularPrice>p.price?`<span class="old">${money(p.regularPrice,p)}</span>`:''}<span class="price">${money(p.price,p)}</span></div><button class="button add" data-id="${p.id}">${t('add')}</button></div></article>`).join(''):`<div class="empty">${t('empty')}</div>`}
function renderCart(){const lines=Object.entries(cart).map(([key,item])=>{const p=products.find(x=>x.id===item.productId);if(!p)return '';const safeKey=escapeHtml(key),choices=[item.color,item.size,item.style].filter(Boolean).map(optionText).join(' | '),price=Number(item.price??p.price);return `<div class="cart-line"><img src="${item.image||p.images[0]}" alt=""><div><strong>${language==='he'?p.nameHe:p.nameEn}</strong>${choices?`<small><br>${choices}</small>`:''}<div>${money(price,p)}</div><div class="qty"><button data-action="minus" data-key="${safeKey}">−</button><span>${item.qty}</span><button data-action="plus" data-key="${safeKey}">+</button></div></div><button class="remove" data-action="remove" data-key="${safeKey}">${t('remove')}</button></div>`}).join('');document.querySelector('#cartLines').innerHTML=lines||`<div class="empty">${t('emptyCart')}</div>`;const count=Object.values(cart).reduce((a,b)=>a+b.qty,0),totalIls=Object.values(cart).reduce((sum,item)=>sum+Number(item.price??products.find(p=>p.id===item.productId)?.price??0)*item.qty,0),totalUsd=Object.values(cart).reduce((sum,item)=>{const p=products.find(x=>x.id===item.productId),price=Number(item.price??p?.price);return sum+(p?(usdAmount(price,p)||0)*item.qty:0)},0);document.querySelector('#cartCount').textContent=count;document.querySelector('#cartTotal').innerHTML=`<span>${t('total')}</span><span>${language==='he'?`${totalIls.toLocaleString('he-IL')} ש״ח`:`$${totalUsd.toFixed(2)}`}</span>`;document.querySelector('#checkout').disabled=!count}
const detailModal=document.createElement('div');detailModal.className='product-detail-modal';detailModal.innerHTML='<div class="product-detail-card" role="dialog" aria-modal="true"><button class="product-detail-close" aria-label="סגירה">×</button><div class="product-detail-gallery"><img class="product-detail-main" alt=""><div class="product-detail-thumbs"></div><div class="product-detail-video-wrap"><video class="product-detail-video" controls playsinline muted preload="metadata"></video><button class="product-detail-video-preview" type="button" aria-label="הפעלת הווידאו"><img alt=""><span aria-hidden="true">▶</span></button></div></div><div class="product-detail-copy"><h2></h2><div class="product-detail-price"></div><p></p><div class="product-detail-options variant-fields"></div><button class="button product-detail-add" type="button"></button></div></div>';document.body.append(detailModal);
let productDetailScrollY=0;
function openProduct(p){const images=p.images?.filter(Boolean)||[],main=detailModal.querySelector('.product-detail-main'),thumbs=detailModal.querySelector('.product-detail-thumbs'),video=detailModal.querySelector('.product-detail-video'),videoWrap=detailModal.querySelector('.product-detail-video-wrap'),videoPreview=detailModal.querySelector('.product-detail-video-preview'),previewImage=videoPreview.querySelector('img');main.src=images[0]||'';main.alt=language==='he'?p.nameHe:p.nameEn;thumbs.innerHTML=images.map((src,i)=>`<button class="${i===0?'active':''}" data-detail-image="${i}"><img src="${src}" alt=""></button>`).join('');const productNumber=String(p.sku||'').match(/(\d+)$/)?.[1],videoSrc=p.videos?.[0]||(productNumber?`products-images/product${String(Number(productNumber)).padStart(2,'0')}-video.mp4`:'');video.pause();video.muted=true;video.defaultMuted=true;video.poster=images[0]||'';previewImage.src=images[0]||'';videoPreview.hidden=false;videoWrap.style.display=videoSrc?'block':'none';if(videoSrc){video.src=videoSrc;video.load()}else{video.removeAttribute('src');video.removeAttribute('poster')}video.onerror=()=>{videoWrap.style.display='none';video.removeAttribute('src')};detailModal.querySelector('h2').textContent=language==='he'?p.nameHe:p.nameEn;detailModal.querySelector('.product-detail-price').textContent=money(p.price,p);detailModal.querySelector('p').innerHTML=cleanDescription(language==='he'?(p.descriptionHe||''):(p.descriptionEn||''));detailModal.querySelector('.product-detail-options').innerHTML=variantSelect(t('color'),'color',p.colors)+variantSelect(t('size'),'size',p.sizes);detailModal.querySelector('.product-detail-add').textContent=t('add');detailModal.dataset.product=p.id;productDetailScrollY=window.scrollY;document.body.style.top=`-${productDetailScrollY}px`;document.body.classList.add('product-detail-open');detailModal.classList.add('open');detailModal.querySelector('.product-detail-card').scrollTop=0;detailModal.querySelector('.product-detail-close').focus()}
function closeProductDetail(){detailModal.querySelector('.product-detail-video').pause();detailModal.classList.remove('open');document.body.classList.remove('product-detail-open');document.body.style.top='';window.scrollTo(0,productDetailScrollY)}
detailModal.addEventListener('click',e=>{const preview=e.target.closest('.product-detail-video-preview');if(preview){const video=detailModal.querySelector('.product-detail-video');preview.hidden=true;video.muted=true;video.play().catch(()=>{preview.hidden=false});return}const add=e.target.closest('.product-detail-add');if(add){const p=products.find(x=>x.id===detailModal.dataset.product),selects=[...detailModal.querySelectorAll('.product-detail-options select')];if(selects.some(s=>!s.value)){selects.find(s=>!s.value).focus();return}const choice=Object.fromEntries(selects.map(s=>[s.name,s.value])),key=[p.id,choice.color,choice.size,choice.style].filter(Boolean).join('::');cart[key]??={productId:p.id,qty:0,...choice,price:selectedPrice(p,choice),image:imageForColor(p,choice.color)};cart[key].qty+=1;saveCart();closeProductDetail();drawer.classList.add('open');return}const thumb=e.target.closest('[data-detail-image]');if(thumb){detailModal.querySelector('.product-detail-main').src=thumb.querySelector('img').src;detailModal.querySelectorAll('[data-detail-image]').forEach(x=>x.classList.toggle('active',x===thumb));return}if(e.target===detailModal||e.target.closest('.product-detail-close'))closeProductDetail()});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&detailModal.classList.contains('open'))closeProductDetail()});
productsEl.addEventListener('click',e=>{const b=e.target.closest('.add');if(!b){if(e.target.closest('select'))return;const card=e.target.closest('[data-product]');if(card)openProduct(products.find(x=>x.id===card.dataset.product));return}const card=b.closest('[data-product]'),p=products.find(x=>x.id===b.dataset.id),selects=[...card.querySelectorAll('select')];if(selects.some(s=>!s.value)){selects.find(s=>!s.value).focus();return}const choice=Object.fromEntries(selects.map(s=>[s.name,s.value])),key=[p.id,choice.color,choice.size,choice.style].filter(Boolean).join('::');cart[key]??={productId:p.id,qty:0,...choice,price:selectedPrice(p,choice),image:imageForColor(p,choice.color)};cart[key].qty+=1;saveCart();drawer.classList.add('open')});
document.querySelector('#cartLines').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const {key,action}=b.dataset,item=cart[key];if(action==='plus')item.qty+=1;if(action==='minus')item.qty=Math.max(item.qty-1,0);if(action==='remove'||item.qty===0)delete cart[key];saveCart()});
productsEl.addEventListener('change',event=>{const select=event.target.closest('.variant-fields select');if(!select)return;const card=select.closest('[data-product]'),product=products.find(item=>item.id===card?.dataset.product),choice=Object.fromEntries([...card.querySelectorAll('.variant-fields select')].map(item=>[item.name,item.value])),image=card?.querySelector('.product-image-wrap>img');if(product&&image&&select.name==='color')image.src=imageForColor(product,select.value);if(product)card.querySelector('.price').textContent=money(selectedPrice(product,choice),product)});
detailModal.addEventListener('change',event=>{const select=event.target.closest('.product-detail-options select');if(!select)return;const product=products.find(item=>item.id===detailModal.dataset.product),choice=Object.fromEntries([...detailModal.querySelectorAll('.product-detail-options select')].map(item=>[item.name,item.value])),src=product&&imageForColor(product,choice.color);if(src&&select.name==='color'){detailModal.querySelector('.product-detail-main').src=src;detailModal.querySelectorAll('[data-detail-image]').forEach(button=>button.classList.toggle('active',button.querySelector('img').src===new URL(src,location.href).href))}if(product)detailModal.querySelector('.product-detail-price').textContent=money(selectedPrice(product,choice),product)});
document.addEventListener('naya-language-change',event=>{language=event.detail;localStorage.setItem('naya_store_language',language);applyLanguage()});searchEl.addEventListener('input',renderProducts);categoryEl.addEventListener('change',renderProducts);document.querySelector('#cartButton').onclick=()=>drawer.classList.add('open');document.querySelector('#continueShopping').onclick=()=>drawer.classList.remove('open');document.querySelector('#closeCart').onclick=()=>drawer.classList.remove('open');document.querySelector('#checkout').onclick=()=>alert(language==='he'?'העגלה והסכום מוכנים. חיבור התשלום יופעל לאחר העברת מסוף טרנזילה.':'The cart and total are ready. Payment will be enabled after the Tranzila terminal is transferred.');applyLanguage();loadRate();
const modelLightbox=document.createElement('div');modelLightbox.className='model-lightbox';modelLightbox.setAttribute('aria-hidden','true');modelLightbox.innerHTML='<button class="model-lightbox-close" type="button" aria-label="סגירת תמונה">×</button><img alt="">';document.body.append(modelLightbox);document.querySelector('#modelGallery')?.addEventListener('click',event=>{const image=event.target.closest('.model-gallery img');if(!image)return;modelLightbox.querySelector('img').src=image.src;modelLightbox.classList.add('open');modelLightbox.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'});modelLightbox.addEventListener('click',event=>{if(event.target===modelLightbox||event.target.closest('.model-lightbox-close')){modelLightbox.classList.remove('open');modelLightbox.setAttribute('aria-hidden','true');modelLightbox.querySelector('img').removeAttribute('src');document.body.style.overflow=''}});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&modelLightbox.classList.contains('open'))modelLightbox.querySelector('.model-lightbox-close').click()});
